import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanStackQueryProvider from "@/components/providers/TanStackQueryProvider";
import NextAuthProvider from "@/components/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth/authOptions";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find Job",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackQueryProvider>
          <NextAuthProvider session={session}>{children}</NextAuthProvider>
        </TanStackQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
